[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

body = """
{% if version %}\
## [{{ version }}](https://github.com/JoShMiQueL/sig-maker/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{% set has_pr = commit.message is containing("[[#") %}
{% if has_pr %}{% set parts = commit.message | split(pat=" [[#") %}{% set msg = parts[0] %}{% set pr_link = "[[#" ~ parts[1] %}{% else %}{% set msg = commit.message %}{% endif %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ msg }}{% if commit.breaking %} [**BREAKING**]{% endif %}\
{% if commit.author.name %} by [@{{ commit.author.name }}](https://github.com/{{ commit.author.name }}){% endif %}\
{% if has_pr %} {{ pr_link }}{% elif commit.id %} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/JoShMiQueL/sig-maker/commit/{{ commit.id }})){% endif %}\
{% endfor %}
{% endfor %}

{% set contributors = commits | map(attribute="author.name") | unique | sort %}
### Contributors
{% for contributor in contributors %}
{% if contributor is not containing("[bot]") -%}
- [@{{ contributor }}](https://github.com/{{ contributor }})
{% endif -%}
{% endfor %}
{% if version and previous.version %}\
**Full Changelog**: https://github.com/JoShMiQueL/sig-maker/compare/{{ previous.version }}...{{ version }}
{% endif %}\
"""

footer = """
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  { pattern = '\(#([0-9]+)\)', replace = "[[#$1](https://github.com/JoShMiQueL/sig-maker/pull/$1)]" },
]
commit_parsers = [
    { message = "update CHANGELOG.md", skip = true },
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^doc", group = "Documentation" },
    { message = "^test", group = "Testing" },
    { message = "^build", group = "Build System" },
    { message = "^ci", group = "CI/CD" },
    { message = "^chore", group = "Miscellaneous" },
    { message = "^revert", group = "Reverts" },
    { message = "^style", skip = true },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
use_branch_tags = false


