[package]
name = "sig-maker-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
colored = { workspace = true }
atty = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "pattern_bench"
harness = false
